### ISSUE TITLE
Comma separated time definitions

### ISSUE THREAD

**Issue by goddenrich** [hjacobs/kube-downscaler#101]
in the README its says:

> Time definitions (e.g. DEFAULT_UPTIME) accept a comma separated list of specifications

but having given a comma separated list of specifications I get the following error:
```
2020-04-10 08:40:36,720 ERROR: Failed to process StatefulSet test/foo : Time spec value "Mon-Thur 09:00-20:00 Europe/London,Fri-Fri 10:00-18:00 Europe/London" does not match format ("Mon-Fri 06:30-20:30 Europe/Berlin" or"2019-01-01T00:00:00+00:00-2019-01-02T12:34:56+00:00")
Traceback (most recent call last):
  File "/kube_downscaler/scaler.py", line 129, in autoscale_resource
    is_uptime = helper.matches_time_spec(
  File "/kube_downscaler/helper.py", line 36, in matches_time_spec
    raise ValueError(
ValueError: Time spec value "Mon-Thur 09:00-20:00 Europe/London,Fri-Fri 10:00-18:00 Europe/London" does not match format ("Mon-Fri 06:30-20:30 Europe/Berlin" or"2019-01-01T00:00:00+00:00-2019-01-02T12:34:56+00:00")
```

**Comment by hjacobs** [comment]
Comma-separated values are accepted, but the error message is misleading. Your first value has an invalid weekday ("Thur" should be "Thu").

I'll fix the error message.
