### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by spirrello** [hjacobs/kube-downscaler#34]
Hi,

Is it possible to add a flag to ignore SSL validation?  I'm getting a ton of these:

r = self.api.get(**kwargs)
File "/usr/local/lib/python3.7/site-packages/pykube/http.py", line 127, in get
return self.session.get(*args, **self.get_kwargs(**kwargs))
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.157.0.1', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'")))
2019-02-27 21:43:03,579 ERROR: Certificate did not match expected hostname: 10.157.0.1. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'Georgia'),), (('localityName', 'Alpharetta'),), (('organizationName', 'kubernetes'),), (('organizationalUnitName', 'at4d-c2'),), (('commonName', '*.acme.dev'),)), 'issuer': ((('countryName', 'US'),), (('stateOrProvinceName', 'Georgia'),), (('localityName', 'Alpharetta'),), (('organizationName', 'acme Technologies'),), (('organizationalUnitName', 'IT'),), (('commonName', '*.acme.com'),)), 'version': 3, 'serialNumber': '7BB0875690FE8FF14EA324BCC3D0C2353BBBE4F4', 'notBefore': 'Apr  3 20:29:00 2018 GMT', 'notAfter': 'Apr  2 20:29:00 2023 GMT', 'subjectAltName': (('DNS', 'kubernetes.default'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'at4d-lvkc2m03'), ('DNS', 'at4d-lvkc2m03.acme.dev'), ('DNS', 'at4d-lvkc2m03.acme.com'), ('DNS', '*.acme.dev'), ('DNS', '*.acme.com'))}
2019-02-27 21:43:03,580 ERROR: Failed to autoscale : HTTPSConnectionPool(host='10.157.0.1', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'")))
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 364, in connect
_match_hostname(cert, self.assert_hostname or server_hostname)
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 374, in _match_hostname
match_hostname(cert, asserted_hostname)    r = self.api.get(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/pykube/http.py", line 127, in get
    return self.session.get(*args, **self.get_kwargs(**kwargs))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.157.0.1', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'")))
2019-02-27 21:43:03,579 ERROR: Certificate did not match expected hostname: 10.157.0.1. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'Georgia'),), (('localityName', 'Alpharetta'),), (('organizationName', 'kubernetes'),), (('organizationalUnitName', 'at4d-c2'),), (('commonName', '*.acme.dev'),)), 'issuer': ((('countryName', 'US'),), (('stateOrProvinceName', 'Georgia'),), (('localityName', 'Alpharetta'),), (('organizationName', 'acme Technologies'),), (('organizationalUnitName', 'IT'),), (('commonName', '*.acme.com'),)), 'version': 3, 'serialNumber': '7BB0875690FE8FF14EA324BCC3D0C2353BBBE4F4', 'notBefore': 'Apr  3 20:29:00 2018 GMT', 'notAfter': 'Apr  2 20:29:00 2023 GMT', 'subjectAltName': (('DNS', 'kubernetes.default'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'at4d-lvkc2m03'), ('DNS', 'at4d-lvkc2m03.acme.dev'), ('DNS', 'at4d-lvkc2m03.acme.com'), ('DNS', '*.acme.dev'), ('DNS', '*.acme.com'))}
2019-02-27 21:43:03,580 ERROR: Failed to autoscale : HTTPSConnectionPool(host='10.157.0.1', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'")))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 364, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 374, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.7/ssl.py", line 323, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.SSLCertVerificationError: ("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.157.0.1', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kube_downscaler/main.py", line 40, in run_loop
    dry_run=dry_run, grace_period=grace_period)
  File "/kube_downscaler/scaler.py", line 119, in scale
    forced_uptime = pods_force_uptime(api, namespace)
  File "/kube_downscaler/scaler.py", line 28, in pods_force_uptime
    for pod in pykube.Pod.objects(api).filter(namespace=(namespace or pykube.all)):
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 133, in __iter__
    return iter(self.query_cache["objects"])
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 123, in query_cache
    cache["response"] = self.execute().json()
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 107, in execute
    r = self.api.get(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/pykube/http.py", line 127, in get
    return self.session.get(*args, **self.get_kwargs(**kwargs))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.157.0.1', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'")))
File "/usr/local/lib/python3.7/ssl.py", line 323, in match_hostname
% (hostname, ', '.join(map(repr, dnsnames))))
ssl.SSLCertVerificationError: ("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.157.0.1', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/kube_downscaler/main.py", line 40, in run_loop
dry_run=dry_run, grace_period=grace_period)
File "/kube_downscaler/scaler.py", line 119, in scale
forced_uptime = pods_force_uptime(api, namespace)
File "/kube_downscaler/scaler.py", line 28, in pods_force_uptime
for pod in pykube.Pod.objects(api).filter(namespace=(namespace or pykube.all)):
File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 133, in __iter__
return iter(self.query_cache["objects"])
File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 123, in query_cache
cache["response"] = self.execute().json()
File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 107, in execute
r = self.api.get(**kwargs)
File "/usr/local/lib/python3.7/site-packages/pykube/http.py", line 127, in get
return self.session.get(*args, **self.get_kwargs(**kwargs))
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.157.0.1', port=443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '10.157.0.1' doesn't match either of 'kubernetes.default', 'kubernetes.default.svc', 'at4d-lvkc2m03', 'at4d-lvkc2m03.acme.dev', 'at4d-lvkc2m03.acme.com', '*.acme.dev', '*.acme.com'")))

**Comment by hjacobs** [comment]
I switched to [pykube-ng](https://github.com/hjacobs/pykube) which honors the `insecure-skip-tls-verify` flag in kubeconfig if set.

**Comment by hjacobs** [comment]
Closing, please tell me if `insecure-skip-tls-verify` did not work for you.

**Comment by spirrello** [comment]
Thanks I will try to test this next week.
